class_name CCFCharacterCollaboratorWindowV01511
extends "res://scripts/ui/character_collaborator_window_v0157.gd"


func _on_generation_completed(job_id: String, job_type: String, data: Variant, metadata: Dictionary) -> void:
	if job_type != "collaborator_vision":
		super._on_generation_completed(job_id, job_type, data, metadata)
		return

	# v0.15.7 handled Vision completion without passing through the v0.15.3
	# completion path, which left the transient "analysing" card active forever.
	_active_collaborator_job_type_v0153 = ""
	_apply_vision_summary_v01511(str(data), metadata)
	_refresh_all()
	call_deferred("_scroll_chat_to_bottom")


func _apply_vision_summary_v01511(summary: String, metadata: Dictionary) -> void:
	var clean_summary := summary.strip_edges()
	var image_name := str(metadata.get("image_name", "Reference image"))
	var image_path := str(metadata.get("image_path", ""))
	var profile_name := str(metadata.get("vision_profile_name", "Vision profile")).strip_edges()
	var model_name := str(metadata.get("vision_model", metadata.get("model", ""))).strip_edges()
	var source_line := "Generated by the configured Vision model"
	if not profile_name.is_empty():
		source_line += " using profile '%s'" % profile_name
	if not model_name.is_empty():
		source_line += " / model '%s'" % model_name

	var wrapped := """VISION DESCRIPTION OF USER-ATTACHED IMAGE
%s.
The original image was inspected by the Vision model. The separate Character Collaborator Text model does NOT receive the image itself. Treat the description below as Vision-derived visual evidence about the whole image: people/characters, appearance, setting, objects, visible text, composition, interactions and apparent activity. Decide what is relevant according to the author's current request. Do not claim to have inspected the original image directly, and preserve the Vision analyst's distinction between observation and uncertain interpretation.

%s""" % [source_line, clean_summary]

	_add_context_item({
		"type": "vision_reference",
		"label": image_name,
		"content": wrapped,
		"vision_description": clean_summary,
		"source_path": image_path,
		"source_role": CCFSettingsService.ROLE_VISION,
		"vision_profile_id": str(metadata.get("vision_profile_id", "")),
		"vision_profile_name": profile_name,
		"vision_model": model_name,
		"context_provenance": "vision_description_of_user_attached_image"
	})

	var session := _active_session()
	var messages_value: Variant = session.get("messages", [])
	var messages: Array = messages_value.duplicate(true) if messages_value is Array else []
	messages.append({
		"role": "vision",
		"content": clean_summary,
		"image_name": image_name,
		"source_path": image_path,
		"vision_profile_name": profile_name,
		"vision_model": model_name,
		"context_provenance": "vision_description_of_user_attached_image"
	})
	session["messages"] = messages
	_store_active_session(session)
	_emit_sessions_changed()
	_status.text = "Vision analysis added to the conversation and reference context. The Text Collaborator will receive the description rather than the original image."


func _build_message_card_v0153(message: Dictionary) -> Control:
	if str(message.get("role", "")) != "vision":
		return super._build_message_card_v0153(message)

	var panel := PanelContainer.new()
	panel.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	var style := StyleBoxFlat.new()
	style.bg_color = Color(0.08, 0.135, 0.135, 1.0)
	style.border_color = Color(0.35, 0.72, 0.68, 0.9)
	style.set_border_width_all(1)
	style.corner_radius_top_left = 8
	style.corner_radius_top_right = 8
	style.corner_radius_bottom_left = 8
	style.corner_radius_bottom_right = 8
	style.content_margin_left = 12
	style.content_margin_right = 12
	style.content_margin_top = 9
	style.content_margin_bottom = 9
	panel.add_theme_stylebox_override("panel", style)

	var content := VBoxContainer.new()
	content.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	content.add_theme_constant_override("separation", 6)
	panel.add_child(content)
	var header := HBoxContainer.new()
	content.add_child(header)
	var who := Label.new()
	var image_name := str(message.get("image_name", "Reference image"))
	who.text = "Vision Analysis — %s" % image_name
	who.modulate = Color(0.60, 0.95, 0.88)
	who.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	header.add_child(who)
	var copy_button := Button.new()
	copy_button.text = "Copy"
	var message_text := str(message.get("content", ""))
	copy_button.pressed.connect(func(): DisplayServer.clipboard_set(message_text))
	header.add_child(copy_button)

	var provenance := Label.new()
	var model_name := str(message.get("vision_model", "")).strip_edges()
	var profile_name := str(message.get("vision_profile_name", "")).strip_edges()
	provenance.text = "Vision-derived reference context" + ((" • %s" % profile_name) if not profile_name.is_empty() else "") + ((" • %s" % model_name) if not model_name.is_empty() else "")
	provenance.modulate = Color(0.58, 0.76, 0.74)
	provenance.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	content.add_child(provenance)

	var body := RichTextLabel.new()
	body.bbcode_enabled = false
	body.fit_content = true
	body.selection_enabled = true
	body.context_menu_enabled = true
	body.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	body.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	body.custom_minimum_size.y = 30
	body.text = message_text
	content.add_child(body)
	return panel
