class_name CCFCharacterCollaboratorWindowV0157
extends "res://scripts/ui/character_collaborator_window_v0156.gd"


func _on_image_selected(path: String) -> void:
	if _generation_service == null or not _generation_service.has_method("queue_collaborator_vision_summary"):
		_status.text = "The active generation service does not support Collaborator Vision analysis."
		return

	var vision_profile := CCFSettingsService.profile_for_role(_settings, CCFSettingsService.ROLE_VISION)
	var vision_model := str(vision_profile.get("model", "")).strip_edges()
	var vision_profile_name := str(vision_profile.get("name", "Vision profile")).strip_edges()
	if vision_profile_name.is_empty():
		vision_profile_name = "Vision profile"
	var retry_count := int((_settings.get("generation", {}) as Dictionary).get("retry_count", 1))
	var session := _active_session()
	var result: Dictionary = _generation_service.call(
		"queue_collaborator_vision_summary",
		path,
		vision_profile,
		retry_count,
		str(session.get("session_id", ""))
	)
	if not bool(result.get("ok", false)):
		_status.text = str(result.get("error", "Could not analyse reference image with the configured Vision model."))
		return

	var model_suffix := ""
	if not vision_model.is_empty():
		model_suffix = " (%s)" % vision_model
	_status.text = "Analysing %s with Vision: %s%s. The Text model will receive only the resulting full-scene description, not the original image." % [path.get_file(), vision_profile_name, model_suffix]
	_refresh_action_state()


func _on_generation_completed(_job_id: String, job_type: String, data: Variant, metadata: Dictionary) -> void:
	if job_type != "collaborator_vision":
		super._on_generation_completed(_job_id, job_type, data, metadata)
		return
	_apply_vision_summary_v0157(str(data), metadata)
	_refresh_all()


func _apply_vision_summary_v0157(summary: String, metadata: Dictionary) -> void:
	var image_name := str(metadata.get("image_name", "Reference image"))
	var image_path := str(metadata.get("image_path", ""))
	var profile_name := str(metadata.get("vision_profile_name", "Vision profile")).strip_edges()
	var model_name := str(metadata.get("vision_model", metadata.get("model", ""))).strip_edges()
	var source_line := "Generated by the configured Vision model"
	if not profile_name.is_empty():
		source_line += " using profile '%s'" % profile_name
	if not model_name.is_empty():
		source_line += " / model '%s'" % model_name

	var wrapped := """VISION DESCRIPTION OF USER-ATTACHED IMAGE
%s.
The original image was inspected by the Vision model. The separate Character Collaborator Text model does NOT receive the image itself. Treat the description below as Vision-derived visual evidence about the whole image: people/characters, appearance, setting, objects, visible text, composition, interactions and apparent activity. Decide what is relevant according to the author's current request. Do not claim to have inspected the original image directly, and preserve the Vision analyst's distinction between observation and uncertain interpretation.

%s""" % [source_line, summary.strip_edges()]

	_add_context_item({
		"type": "vision_reference",
		"label": image_name,
		"content": wrapped,
		"vision_description": summary.strip_edges(),
		"source_path": image_path,
		"source_role": CCFSettingsService.ROLE_VISION,
		"vision_profile_id": str(metadata.get("vision_profile_id", "")),
		"vision_profile_name": profile_name,
		"vision_model": model_name,
		"context_provenance": "vision_description_of_user_attached_image"
	})
	_status.text = "Vision analysis added as full-scene image context. The Text Collaborator will receive this description rather than the original image."
