extends SceneTree

const COMPLETION_SERVICE = preload(
	"res://scripts/services/collaborator_completion_service_v01535.gd"
)
const DESTINATION_WINDOW = preload(
	"res://scripts/ui/collaborator_completion_destination_window_v01535.gd"
)


func _init() -> void:
	call_deferred("_run")


func _run() -> void:
	var template := CCFTemplateService.load_default_template()
	assert(not template.is_empty(), "v0.15.35 regression requires the default template.")

	var blank := CCFStorageService.new_character_record()
	var blank_id := str(blank.get("character_id", ""))
	assert(
		COMPLETION_SERVICE.is_effectively_empty_character(blank, template),
		"A fresh untouched character must be considered an empty Workspace slot."
	)
	assert(
		COMPLETION_SERVICE.recommended_destination(blank, template)
		== COMPLETION_SERVICE.DEST_CURRENT_EMPTY,
		"An empty Workspace must recommend reusing the current character slot."
	)
	var blank_options := COMPLETION_SERVICE.destination_options(blank, template)
	assert(
		_option_ids(blank_options).has(COMPLETION_SERVICE.DEST_CURRENT_EMPTY),
		"Empty Workspace routing must expose the current-slot destination."
	)
	assert(
		_option_ids(blank_options).has(COMPLETION_SERVICE.DEST_SAME_PROJECT_NEW),
		"Empty Workspace routing must still allow creating a sibling character."
	)
	assert(
		_option_ids(blank_options).has(COMPLETION_SERVICE.DEST_NEW_PROJECT),
		"Completion routing must expose a separate-project destination."
	)

	var occupied := blank.duplicate(true)
	CCFStorageService.set_value_at_path(
		occupied,
		"concept.prompt",
		"An existing authored character that must never be overwritten silently."
	)
	assert(
		not COMPLETION_SERVICE.is_effectively_empty_character(occupied, template),
		"Meaningful concept content must make the current Workspace occupied."
	)
	assert(
		COMPLETION_SERVICE.recommended_destination(occupied, template)
		== COMPLETION_SERVICE.DEST_SAME_PROJECT_NEW,
		"An occupied Workspace must recommend a new character in the same project."
	)
	assert(
		not _option_ids(COMPLETION_SERVICE.destination_options(occupied, template)).has(
			COMPLETION_SERVICE.DEST_CURRENT_EMPTY
		),
		"An occupied character must never expose the empty-slot replacement route."
	)

	var source := {
		"format": "character_card_forge_collaborator_source",
		"format_version": 1,
		"source_context_id": "source-v01535-regression",
		"source_type": "character",
		"label": "Source Character",
		"snapshot": {"character_id": "source-character"},
		"author_intent": "Create a future version.",
		"provenance": {
			"derivation": {
				"source_project_id": "source-project",
				"source_character_id": "source-character",
				"source_character_name": "Source Character",
				"derivation_type": "future_version"
			}
		}
	}
	var blueprint_payload := {
		"handoff_mode": "blueprint",
		"suggested_name": "Future Character",
		"concept_prompt": "A complete future-version Generation Concept."
	}
	var blank_materialised := COMPLETION_SERVICE.materialise_character(
		blueprint_payload,
		"Future Character Session",
		template,
		COMPLETION_SERVICE.DEST_CURRENT_EMPTY,
		source,
		blank
	)
	assert(bool(blank_materialised.get("ok", false)), "Blueprint materialisation must succeed.")
	var blank_record: Dictionary = blank_materialised.get("character", {})
	assert(
		str(blank_record.get("character_id", "")) == blank_id,
		"Reusing an empty Workspace slot must preserve its existing character ID."
	)
	assert(
		str(CCFStorageService.get_value_at_path(blank_record, "concept.prompt", ""))
		== "A complete future-version Generation Concept.",
		"Blueprint routing must preserve the generated Generation Concept."
	)
	var blank_provenance: Dictionary = blank_record.get("provenance", {})
	var completion_provenance: Dictionary = blank_provenance.get("character_collaborator", {})
	assert(
		str(completion_provenance.get("destination", ""))
		== COMPLETION_SERVICE.DEST_CURRENT_EMPTY,
		"Completion provenance must record the selected destination."
	)
	assert(
		str((blank_provenance.get("derivation", {}) as Dictionary).get("source_character_id", ""))
		== "source-character",
		"v0.15.35 must carry v0.15.34 derivation provenance into the completed standalone character."
	)

	var detailed_fields := {}
	for raw_field in CCFTemplateService.generation_fields(template):
		if not raw_field is Dictionary:
			continue
		var field: Dictionary = raw_field
		var field_id := str(field.get("id", ""))
		var field_path := str(field.get("path", ""))
		if field_path == "character.name":
			detailed_fields[field_id] = "Detailed Character"
		elif field_path == "character.description":
			detailed_fields[field_id] = "Detailed physical description generated by Collaborator."
	var detailed_payload := {
		"handoff_mode": "detailed_workspace_draft",
		"suggested_name": "Detailed Character",
		"concept_prompt": "Detailed character blueprint.",
		"fields": detailed_fields,
		"alternate_greetings": ["Greeting one", "Greeting two"],
		"lorebook": {"entries": [{"keys": ["campus"], "content": "Campus lore."}]}
	}
	var detailed_materialised := COMPLETION_SERVICE.materialise_character(
		detailed_payload,
		"Detailed Session",
		template,
		COMPLETION_SERVICE.DEST_SAME_PROJECT_NEW,
		source
	)
	assert(bool(detailed_materialised.get("ok", false)), "Detailed Workspace materialisation must succeed.")
	var detailed_record: Dictionary = detailed_materialised.get("character", {})
	var greetings_value: Variant = CCFStorageService.get_value_at_path(
		detailed_record,
		"character.alternate_greetings",
		[]
	)
	assert(greetings_value is Array and (greetings_value as Array).size() == 2, "Detailed routing must preserve Alternative Greetings.")
	var book_value: Variant = CCFStorageService.get_value_at_path(
		detailed_record,
		"character.character_book",
		{}
	)
	assert(book_value is Dictionary and ((book_value as Dictionary).get("entries", []) as Array).size() == 1, "Detailed routing must preserve Character Lorebook entries.")

	var chooser := DESTINATION_WINDOW.new() as CCFCollaboratorCompletionDestinationWindowV01535
	root.add_child(chooser)
	await process_frame
	chooser.open_for_completion_v01535(blank, template, "Regression Project", "Untitled Character")
	await process_frame
	assert(
		chooser.selected_destination_v01535() == COMPLETION_SERVICE.DEST_CURRENT_EMPTY,
		"Destination chooser must default an empty Workspace to the current empty slot."
	)
	chooser.hide()
	chooser.open_for_completion_v01535(occupied, template, "Regression Project", "Existing Character")
	await process_frame
	assert(
		chooser.selected_destination_v01535() == COMPLETION_SERVICE.DEST_SAME_PROJECT_NEW,
		"Destination chooser must default an occupied Workspace to a new same-project character."
	)
	assert(
		not chooser.destination_ids_v01535().has(COMPLETION_SERVICE.DEST_CURRENT_EMPTY),
		"Destination chooser must not offer current-slot replacement when the character is occupied."
	)

	var scene := load("res://scenes/main.tscn") as PackedScene
	assert(scene != null, "The real main scene must load for v0.15.35 regression coverage.")
	var app := scene.instantiate()
	root.add_child(app)
	await process_frame
	await process_frame
	await process_frame
	await process_frame
	var workspace_value: Variant = app.get("_workspace")
	assert(workspace_value is CCFWorkspaceV01535View, "The real main scene must install the v0.15.35 Workspace.")
	var workspace := workspace_value as CCFWorkspaceV01535View
	var capabilities := workspace.collaborator_completion_capabilities_v01535()
	assert(bool(capabilities.get("empty_workspace_reuse", false)), "v0.15.35 must support empty Workspace reuse.")
	assert(bool(capabilities.get("same_project_new_character", false)), "v0.15.35 must support safe same-project character creation.")
	assert(bool(capabilities.get("new_project_destination", false)), "v0.15.35 must support a separate-project destination.")
	assert(not bool(capabilities.get("occupied_character_overwrite", true)), "v0.15.35 must never silently overwrite an occupied character.")
	assert(bool(capabilities.get("replacement_compare_apply_reserved_v01536", false)), "Occupied replacement must remain reserved for v0.15.36 Compare & Apply.")
	var live_collaborator_value: Variant = workspace.get("_character_collaborator_window")
	assert(live_collaborator_value is CCFCharacterCollaboratorWindowV01535, "Live Workspace must install the v0.15.35 Collaborator window.")
	var live_destination_value: Variant = workspace.get("_completion_destination_window_v01535")
	assert(live_destination_value is CCFCollaboratorCompletionDestinationWindowV01535, "Live Workspace must install the v0.15.35 completion destination chooser.")

	var found_pending_menu := false
	for node in workspace.find_children("*", "MenuButton", true, false):
		if not node is MenuButton or (node as MenuButton).text != "Author":
			continue
		var popup := (node as MenuButton).get_popup()
		for index in range(popup.item_count):
			if popup.get_item_text(index) == "Place Pending Collaborator Completion…":
				found_pending_menu = true
				break
	assert(found_pending_menu, "Author menu must expose pending completion recovery.")

	var app_settings_value: Variant = app.get("_settings")
	var app_settings: Dictionary = app_settings_value if app_settings_value is Dictionary else {}
	var project := CCFStorageService.new_project()
	var original_id := CCFStorageService.active_character_id(project)
	workspace.load_project(project, template, app_settings)
	await process_frame
	var first_result := workspace.apply_collaborator_completion_v01535(
		blueprint_payload,
		"First Completion",
		COMPLETION_SERVICE.DEST_CURRENT_EMPTY,
		source
	)
	assert(bool(first_result.get("ok", false)), "Live empty-slot completion must succeed.")
	var after_first_value: Variant = workspace.get("_project_container")
	assert(after_first_value is Dictionary, "Workspace must retain a project container after completion.")
	var after_first: Dictionary = after_first_value
	var first_characters: Array = after_first.get("characters", [])
	assert(first_characters.size() == 1, "Empty-slot completion must not create a duplicate character.")
	assert(CCFStorageService.character_index(after_first, original_id) >= 0, "Empty-slot completion must preserve the original character ID.")
	var original_after_first := CCFStorageService.get_character(after_first, original_id)
	var original_concept := str(CCFStorageService.get_value_at_path(original_after_first, "concept.prompt", ""))
	assert(original_concept == "A complete future-version Generation Concept.", "Empty-slot completion must populate the current character.")

	var second_payload := blueprint_payload.duplicate(true)
	second_payload["suggested_name"] = "Sibling Character"
	second_payload["concept_prompt"] = "A second completed character that belongs beside the first one."
	var second_result := workspace.apply_collaborator_completion_v01535(
		second_payload,
		"Second Completion",
		COMPLETION_SERVICE.DEST_SAME_PROJECT_NEW,
		source
	)
	assert(bool(second_result.get("ok", false)), "Live same-project completion must succeed.")
	var after_second: Dictionary = workspace.get("_project_container")
	var second_characters: Array = after_second.get("characters", [])
	assert(second_characters.size() == 2, "Occupied completion must add a new sibling character to the same project.")
	var original_after_second := CCFStorageService.get_character(after_second, original_id)
	assert(
		str(CCFStorageService.get_value_at_path(original_after_second, "concept.prompt", "")) == original_concept,
		"Adding the sibling character must leave the occupied original character unchanged."
	)
	assert(
		str(second_result.get("character_id", "")) != original_id,
		"Same-project completion must receive its own character ID."
	)

	var main_script := app.get_script() as Script
	assert(main_script != null and main_script.resource_path.ends_with("main_v01535.gd"), "The active app shell must be v0.15.35.")

	app.queue_free()
	chooser.queue_free()
	await process_frame
	print("v0.15.35 Collaborator completion routing regression passed")
	quit(0)


func _option_ids(options: Array[Dictionary]) -> Array[String]:
	var result: Array[String] = []
	for option in options:
		result.append(str(option.get("id", "")))
	return result
